/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.tbruyelle.rxpermissions2;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int coordinatorLayoutStyle = 0x7f0300b0;
        public static final int font = 0x7f0300e4;
        public static final int fontProviderAuthority = 0x7f0300e6;
        public static final int fontProviderCerts = 0x7f0300e7;
        public static final int fontProviderFetchStrategy = 0x7f0300e8;
        public static final int fontProviderFetchTimeout = 0x7f0300e9;
        public static final int fontProviderPackage = 0x7f0300ea;
        public static final int fontProviderQuery = 0x7f0300eb;
        public static final int fontStyle = 0x7f0300ec;
        public static final int fontWeight = 0x7f0300ee;
        public static final int keylines = 0x7f030124;
        public static final int layout_anchor = 0x7f030129;
        public static final int layout_anchorGravity = 0x7f03012a;
        public static final int layout_behavior = 0x7f03012b;
        public static final int layout_dodgeInsetEdges = 0x7f030157;
        public static final int layout_insetEdge = 0x7f030160;
        public static final int layout_keyline = 0x7f030161;
        public static final int statusBarBackground = 0x7f0301eb;
    }
    public static final class bool {
        private bool() {}

        public static final int abc_action_bar_embed_tabs = 0x7f040000;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f0500b5;
        public static final int notification_icon_bg_color = 0x7f0500b6;
        public static final int ripple_material_light = 0x7f0500c6;
        public static final int secondary_text_default_material_light = 0x7f0500c8;
    }
    public static final class dimen {
        private dimen() {}

        public static final int compat_button_inset_horizontal_material = 0x7f060056;
        public static final int compat_button_inset_vertical_material = 0x7f060057;
        public static final int compat_button_padding_horizontal_material = 0x7f060058;
        public static final int compat_button_padding_vertical_material = 0x7f060059;
        public static final int compat_control_corner_material = 0x7f06005a;
        public static final int notification_action_icon_size = 0x7f060108;
        public static final int notification_action_text_size = 0x7f060109;
        public static final int notification_big_circle_margin = 0x7f06010a;
        public static final int notification_content_margin_start = 0x7f06010b;
        public static final int notification_large_icon_height = 0x7f06010c;
        public static final int notification_large_icon_width = 0x7f06010d;
        public static final int notification_main_column_padding_top = 0x7f06010e;
        public static final int notification_media_narrow_margin = 0x7f06010f;
        public static final int notification_right_icon_size = 0x7f060110;
        public static final int notification_right_side_padding_top = 0x7f060111;
        public static final int notification_small_icon_background_padding = 0x7f060112;
        public static final int notification_small_icon_size_as_large = 0x7f060113;
        public static final int notification_subtext_size = 0x7f060114;
        public static final int notification_top_pad = 0x7f060115;
        public static final int notification_top_pad_large_text = 0x7f060116;
    }
    public static final class drawable {
        private drawable() {}

        public static final int notification_action_background = 0x7f0700ba;
        public static final int notification_bg = 0x7f0700bb;
        public static final int notification_bg_low = 0x7f0700bc;
        public static final int notification_bg_low_normal = 0x7f0700bd;
        public static final int notification_bg_low_pressed = 0x7f0700be;
        public static final int notification_bg_normal = 0x7f0700bf;
        public static final int notification_bg_normal_pressed = 0x7f0700c0;
        public static final int notification_icon_background = 0x7f0700c1;
        public static final int notification_template_icon_bg = 0x7f0700c2;
        public static final int notification_template_icon_low_bg = 0x7f0700c3;
        public static final int notification_tile_bg = 0x7f0700c4;
        public static final int notify_panel_notification_icon_bg = 0x7f0700c5;
    }
    public static final class id {
        private id() {}

        public static final int action_container = 0x7f080012;
        public static final int action_divider = 0x7f080014;
        public static final int action_image = 0x7f080016;
        public static final int action_text = 0x7f08001d;
        public static final int actions = 0x7f08001e;
        public static final int async = 0x7f080029;
        public static final int blocking = 0x7f080032;
        public static final int bottom = 0x7f080033;
        public static final int chronometer = 0x7f08004c;
        publ